## Numpy
  1.python library for creating 
    N-dimensional arrays
  2.Ability to quickly Broadcasting funtions
  3.Built in linear algebra statistical
    distribution trignometric and random number capabiltiies

In [2]:
import numpy as np


In [3]:
mylist =[1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr=np.array(mylist)

In [8]:
myarr

array([1, 2, 3])

In [9]:
type(myarr)

numpy.ndarray

In [10]:
mymatrix=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [28]:
len(np.linspace(0,5,21))

21

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(1)

array([0.63951441])

In [33]:
np.random.rand(5,2)

array([[0.6731457 , 0.93384635],
       [0.73027852, 0.59266455],
       [0.38779378, 0.28810637],
       [0.15357927, 0.93790033],
       [0.16029152, 0.58145041]])

In [34]:
np.random.randn(10)

array([ 0.60501213, -0.7972225 , -0.04445813,  0.20235651,  0.42119407,
        1.2666887 ,  0.25232583, -0.40938557, -0.00958927,  1.64499388])

In [36]:
np.random.randn(5,4)

array([[-0.03401993,  0.66528692, -0.18294978,  0.04330767],
       [ 0.00839854,  0.2629569 , -0.87345229, -1.19483662],
       [ 0.43622361, -0.44039339,  2.08898541,  0.551329  ],
       [-0.06520552, -1.13364532, -0.04153443,  0.63221597],
       [-0.29181404,  1.28706792,  0.25218247, -0.29623122]])

In [37]:
np.random.randint(0,101,(4,5))

array([[14,  1, 77, 40, 83],
       [37, 85, 17,  7, 23],
       [60, 40,  5, 62, 18],
       [ 7, 21, 76, 61, 90]])

In [39]:
np.random.randint(0,101,10)

array([38, 38, 10, 40, 58, 93,  5, 99, 80, 49])

In [40]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [41]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [43]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [60]:
arr=np.arange(0,18)

In [61]:
arr.reshape(6,3) # 6*3=18

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
ranarr=np.random.randint(0,101,10)

In [64]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [66]:
ranarr.max()

92

In [67]:
ranarr.min()

4

In [69]:
ranarr.argmax()

7

In [71]:
ranarr.argmin()

3

In [72]:
ranarr.dtype

dtype('int32')

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [74]:
arr.shape

(18,)

In [76]:
arr=arr.reshape(6,3)

In [77]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [78]:
arr.shape

(6, 3)

In [79]:
arr.reshape(18,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17]])

In [80]:
arr.reshape(1,18)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])