In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5]=100

In [11]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr= np.arange(0,11)

In [19]:
slice_of_arr=arr[0:5]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [21]:
slice_of_arr[:]=99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_copy=arr.copy()

In [25]:
arr_copy[:]=100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [29]:
arr_2d=np.array([[2,3,4,],[2,4,5],[4,9,8]])

In [30]:
arr_2d

array([[2, 3, 4],
       [2, 4, 5],
       [4, 9, 8]])

In [31]:
arr_2d.shape

(3, 3)

In [32]:
arr_2d[0]

array([2, 3, 4])

In [33]:
arr_2d[2]

array([4, 9, 8])

In [34]:
arr_2d[1,1]

4

In [36]:
arr_2d[0,1]

3

In [37]:
arr_2d[:2]

array([[2, 3, 4],
       [2, 4, 5]])

In [39]:
arr_2d[1:3,0:2]

array([[2, 4],
       [4, 9]])

In [40]:
arr_2d[0:2,1:3]

array([[3, 4],
       [4, 5]])

In [41]:
arr=np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [44]:
bool_arr=arr>4

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])